### ISSUE TITLE
Formal Citations.

### ISSUE THREAD

**Issue by JingshuaiLiu** [MLI-lab/ConvDecoder#2]
Hello,

Good work. However, I only found the pre-print versions of the two papers pertaining to un-trained models.  Could you kindly provide the citations in a formal form, e.g. accepted by a conference or a journal, to better refer to in the future works?

Thanks a lot!

**Comment by mersad95zd** [comment]
Hi, 

Thanks for reaching out. This work is currently undergoing the process of being published in IEEE Transaction on Computational Imaging, and hence we'll add that to the repo in a few weeks. For now, you may refer to it as the arxiv version or simply replace the journal name by ``IEEE Transaction on Computational Imaging." 

I think that addresses your request, so I'm closing it.
